version: '3.5'

services:
  kotlin-api:
    container_name: 'kotlin-api'
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: db_retail